spring.application.name: spring-customer-app

management:
  metrics:
    export:
      datadog:
        api-key:
        application-key:
        host-tag: ${spring.application.name}.voicestreams.com
        step: 10s